import Anderson4D.DetParametrix.Paper42_Moment.R324FirstLeftPrimitiveLocalFactor

/-! # Heterogeneous edge states for an R-324 within-half prefix -/

set_option warningAsError true
set_option autoImplicit false

namespace Anderson4D

noncomputable section

/-- Edge slot immediately to the left of an internal pairing vertex. -/
def r324InternalVertexEdgeSlot {m : ℕ} (i : Fin m) : Fin (m + 1) :=
  ⟨i.val + 1, by omega⟩

/-- A processed analytic prefix together with its current named kernels. -/
structure R324WithinHalfEdgeState (m : ℕ) where
  processed : List (R322ExtractionStep m)
  edges : Fin (m + 1) → T4 → ℝ

def r324InitialWithinHalfEdgeState (m : ℕ) :
    R324WithinHalfEdgeState m where
  processed := []
  edges := fun _ => greenFn

def R324WithinHalfEdgeState.active
    {m : ℕ} (state : R324WithinHalfEdgeState m) :
    Finset (Fin m) :=
  r322AnalyticActiveCarrier state.processed

/-- Candidate chain slots before a current block.  Slot zero is the
incoming external edge, so this set is always nonempty. -/
def r324WithinHalfPredecessorCandidates
    {m : ℕ} (state : R324WithinHalfEdgeState m)
    (step : R322ExtractionStep m) :
    Finset (Fin (m + 1)) :=
  {0} ∪
    (state.active.filter fun i => i < step.1.1).image
      r324InternalVertexEdgeSlot

theorem r324WithinHalfPredecessorCandidates_nonempty
    {m : ℕ} (state : R324WithinHalfEdgeState m)
    (step : R322ExtractionStep m) :
    (r324WithinHalfPredecessorCandidates state step).Nonempty := by
  exact ⟨0, by simp [r324WithinHalfPredecessorCandidates]⟩

/-- Greatest surviving edge slot before the current block. -/
def r324WithinHalfPredecessorSlot
    {m : ℕ} (state : R324WithinHalfEdgeState m)
    (step : R322ExtractionStep m) : Fin (m + 1) :=
  (r324WithinHalfPredecessorCandidates state step).max'
    (r324WithinHalfPredecessorCandidates_nonempty state step)

/-- Certified next step of the actual analytic schedule. -/
structure R324WithinHalfStepContext
    {m : ℕ} (pairing : PartialPairing (Fin m)) where
  state : R324WithinHalfEdgeState m
  step : R322ExtractionStep m
  suffix : List (R322ExtractionStep m)
  schedule_eq :
    r322AnalyticSchedule pairing =
      state.processed ++ step :: suffix

namespace R324WithinHalfStepContext

variable {m : ℕ} {pairing : PartialPairing (Fin m)}
    (ctx : R324WithinHalfStepContext pairing)

theorem step_mem_schedule :
    ctx.step ∈ r322AnalyticSchedule pairing := by
  rw [ctx.schedule_eq]
  simp

theorem block_mem_extractionBlocks :
    ctx.step.2 ∈ extractionBlocks pairing := by
  apply
    (r322AnalyticSchedule_blocks_perm_extractionBlocks
      pairing).mem_iff.mp
  exact List.mem_map.mpr
    ⟨ctx.step, ctx.step_mem_schedule, rfl⟩

theorem blockFullyPaired :
    IsFullyPairedOn pairing ctx.step.2 :=
  extractionBlock_isFullyPairedOn_of_mem
    pairing ctx.step.2 ctx.block_mem_extractionBlocks

theorem blockNonempty : ctx.step.2.Nonempty := by
  have haligned :=
    r322AnalyticSchedule_forall_aligned
      pairing ctx.step ctx.step_mem_schedule
  exact ⟨ctx.step.1.1, haligned.1⟩

theorem one_le_blockOrder :
    1 ≤ residualBlockOrder ctx.step.2 :=
  one_le_residualBlockOrder_of_nonempty
    pairing ctx.step.2 ctx.blockFullyPaired ctx.blockNonempty

def blockOrderIso :
    Fin (2 * residualBlockOrder ctx.step.2) ≃o ctx.step.2 :=
  residualPrimitiveBlockOrderIso
    pairing ctx.step.2 ctx.blockFullyPaired

/-- State slot carrying the `j`th internal edge of the current sparse
block. -/
def internalSlot
    (j : Fin (2 * residualBlockOrder ctx.step.2 - 1)) :
    Fin (m + 1) :=
  r324InternalVertexEdgeSlot
    (ctx.blockOrderIso
      ⟨j.val, by
        have hj := j.isLt
        have hn := ctx.one_le_blockOrder
        omega⟩).1

def internalEdges :
    Fin (2 * residualBlockOrder ctx.step.2 - 1) → T4 → ℝ :=
  fun j => ctx.state.edges (ctx.internalSlot j)

/-- Deterministic primitive kernel generated by the current block. -/
def primitiveKernel
    (ρ : SmoothCutoff) (lam ε : ℝ) : T4 → ℝ :=
  primitiveKernelDiff ρ lam ε
    (residualBlockOrder ctx.step.2)
    ctx.one_le_blockOrder ctx.internalEdges

/-- Current edge immediately leaving the block. -/
def outgoingSlot : Fin (m + 1) :=
  r324InternalVertexEdgeSlot ctx.step.1.2

/-- The genuine block collapse: predecessor, primitive kernel, and the
difference across the current outgoing kernel are integrated as in (4.8). -/
def collapsedKernel
    (ρ : SmoothCutoff) (lam ε : ℝ) : T4 → ℝ :=
  r322Collapse
    (ctx.state.edges
      (r324WithinHalfPredecessorSlot ctx.state ctx.step))
    (ctx.primitiveKernel ρ lam ε)
    (ctx.state.edges ctx.outgoingSlot)

/-- Absorb one actual schedule step at its surviving predecessor slot,
leaving every other named edge unchanged. -/
def absorb
    (ρ : SmoothCutoff) (lam ε : ℝ) :
    R324WithinHalfEdgeState m where
  processed := ctx.state.processed ++ [ctx.step]
  edges := Function.update ctx.state.edges
    (r324WithinHalfPredecessorSlot ctx.state ctx.step)
    (ctx.collapsedKernel ρ lam ε)

@[simp]
theorem absorb_edges_predecessor
    (ρ : SmoothCutoff) (lam ε : ℝ) :
    (ctx.absorb ρ lam ε).edges
        (r324WithinHalfPredecessorSlot ctx.state ctx.step) =
      ctx.collapsedKernel ρ lam ε := by
  simp [absorb]

theorem absorb_edges_of_ne
    (ρ : SmoothCutoff) (lam ε : ℝ)
    (edge : Fin (m + 1))
    (hne :
      edge ≠ r324WithinHalfPredecessorSlot
        ctx.state ctx.step) :
    (ctx.absorb ρ lam ε).edges edge =
      ctx.state.edges edge := by
  simp [absorb, hne]

@[simp]
theorem absorb_active
    (ρ : SmoothCutoff) (lam ε : ℝ) :
    (ctx.absorb ρ lam ε).active =
      ctx.state.active \ ctx.step.2 := by
  simp [R324WithinHalfEdgeState.active, absorb,
    r322AnalyticActiveCarrier_append_singleton]

end R324WithinHalfStepContext

/-- Algebraically reachable states are generated only by actual successive
steps of the fixed analytic schedule and the genuine three-kernel collapse
above.  No desired pointwise factorization is stored in this predicate. -/
inductive R324WithinHalfStateReachable
    {m : ℕ} (pairing : PartialPairing (Fin m))
    (ρ : SmoothCutoff) (lam ε : ℝ) :
    R324WithinHalfEdgeState m → Prop
  | initial :
      R324WithinHalfStateReachable pairing ρ lam ε
        (r324InitialWithinHalfEdgeState m)
  | absorb
      (ctx : R324WithinHalfStepContext pairing)
      (hctx :
        R324WithinHalfStateReachable pairing ρ lam ε ctx.state) :
      R324WithinHalfStateReachable pairing ρ lam ε
        (ctx.absorb ρ lam ε)

/-! ## The empty-prefix predecessor is genuinely free Green -/

theorem firstLeft_predecessor_not_extracted_of_analyticHead
    {m : ℕ} (e₀ : MomentContraction m)
    (hleft : ∃ a b, IsRelFullyPaired e₀.1
      (Finset.univ : Finset (Fin m)) a b)
    (tail : List (R322ExtractionStep m))
    (hschedule :
      r322AnalyticSchedule e₀.1 =
        r324FirstLeftSelectedStep e₀ hleft :: tail) :
    r324FirstLeftPredecessorEdge e₀ hleft ∉
      extractedRightEdges e₀.1 := by
  intro hedge
  obtain ⟨p, hp, hpedge⟩ :=
    exists_extractedPairOfRightEdge e₀.1
      (r324FirstLeftPredecessorEdge e₀ hleft) hedge
  have hpSchedule :
      p ∈ (r322AnalyticSchedule e₀.1).map Prod.fst :=
    (r322AnalyticSchedule_endpoints_perm_extract e₀.1).mem_iff.mpr hp
  obtain ⟨step, hstep, hstepEndpoint⟩ :=
    List.mem_map.mp hpSchedule
  have hright :
      step.1.2 <
        (r324FirstLeftSelectedStep e₀ hleft).1.2 := by
    rw [hstepEndpoint]
    have hv := congrArg Fin.val hpedge
    simp only [extractedRightEdge_val,
      r324FirstLeftPredecessorEdge] at hv
    simp only [r324FirstLeftSelectedStep_endpoint]
    have hab := (selectRel_isRelFullyPaired
      e₀.1 Finset.univ hleft).le
    omega
  have himpossible :
      step ∈ ([] : List (R322ExtractionStep m)) :=
    r322AnalyticSchedule_mem_prefix_of_right_lt
      e₀.1 [] tail
      (r324FirstLeftSelectedStep e₀ hleft)
      step (by simpa using hschedule) hstep hright
  simp at himpossible

theorem productionPredecessor_eq_initialStateEdge
    {m : ℕ} (κ : PartialPairing (Fin m))
    (e₀ : MomentContraction m)
    (hleft : ∃ a b, IsRelFullyPaired e₀.1
      (Finset.univ : Finset (Fin m)) a b)
    (hsig : reductionEndpointSignature κ =
      reductionEndpointSignature e₀.1)
    (tail : List (R322ExtractionStep m))
    (hschedule :
      r322AnalyticSchedule e₀.1 =
        r324FirstLeftSelectedStep e₀ hleft :: tail)
    (xt : Fin (m + 2) → T4) :
    r324ProductionGreenEdgeFactor κ xt
        (r324FirstLeftPredecessorEdge e₀ hleft) =
      ((r324InitialWithinHalfEdgeState m).edges
        (r324FirstLeftPredecessorEdge e₀ hleft)
        (xt (r324FirstLeftPredecessorEdge
              e₀ hleft).castSucc -
          xt (r324FirstLeftPredecessorEdge
              e₀ hleft).succ) : ℝ) := by
  have hnotRef :=
    firstLeft_predecessor_not_extracted_of_analyticHead
      e₀ hleft tail hschedule
  have hset :=
    extractedRightEdges_eq_of_extract_perm κ e₀.1
      (extract_perm_of_reductionEndpointSignature_eq
        κ e₀.1 hsig)
  have hnot :
      r324FirstLeftPredecessorEdge e₀ hleft ∉
        extractedRightEdges κ := by
    rw [hset]
    exact hnotRef
  unfold r324ProductionGreenEdgeFactor
    extractedShortcutGreenEdge originalGreenEdge
    r324InitialWithinHalfEdgeState
  rw [dif_neg hnot, sub_zero]

theorem r324FirstLeftReconstruct_touchingGreenProduct_eq_initialStateLocal
    {m : ℕ} (e₀ : MomentContraction m)
    (hleft : ∃ a b, IsRelFullyPaired e₀.1
      (Finset.univ : Finset (Fin m)) a b)
    (ω : R324FirstLeftOuterCoordinate e₀ hleft)
    (κB : R324FirstLeftBlockCoordinate e₀ hleft)
    (tail : List (R322ExtractionStep m))
    (hschedule :
      r322AnalyticSchedule e₀.1 =
        r324FirstLeftSelectedStep e₀ hleft :: tail)
    (xt : Fin (m + 2) → T4) :
    let κ := (r324FirstLeftReconstruct e₀ hleft ω κB).1.1
    r324FirstLeftTouchingGreenProduct κ e₀ hleft xt =
      (((r324InitialWithinHalfEdgeState m).edges
        (r324FirstLeftPredecessorEdge e₀ hleft)
        (xt (r324FirstLeftPredecessorEdge
              e₀ hleft).castSucc -
          xt (r324FirstLeftPredecessorEdge
              e₀ hleft).succ) : ℝ) : ℂ) *
        ((primitiveChainProduct
          (residualBlockOrder
            (selectedExtractionBlock e₀.1 Finset.univ hleft))
          (r324FirstLeft_one_le_blockOrder e₀ hleft)
          (fun _ => greenFn)
          (r324FirstLeftCarrierTuple e₀ hleft xt) : ℝ) : ℂ) *
        r324ProductionGreenEdgeFactor κ xt
          (r324FirstLeftOutgoingEdge e₀ hleft) := by
  dsimp only
  let κ :=
    (r324FirstLeftReconstruct e₀ hleft ω κB).1.1
  have hsig :
      reductionEndpointSignature κ =
        reductionEndpointSignature e₀.1 := by
    dsimp only [κ]
    rw [r324FirstLeftReconstruct_leftPairing]
    exact
      ((reductionEndpointFiberEquivBlockComplement
        e₀.1 hleft).symm (κB, ω.1)).2
  rw [r324FirstLeftReconstruct_touchingGreenProduct_eq_primitiveLocal]
  rw [productionPredecessor_eq_initialStateEdge
    κ e₀ hleft hsig tail hschedule xt]

end

end Anderson4D
