import Anderson4D.DetParametrix.Paper42_Moment.R324MarkedBlockOpenWord
import Anderson4D.Continuum.OpenEdgeOccupiedLabels

/-!
# Occupied-label realization of the marked R-324 block

This file specializes the generic occupied-label reindexing to the unique
marked residual primitive block.  A genuine ambient selected cell word is
first restricted to that block and then reindexed by an equivalence between
its finite occupied support and the leaves of a Hepp tree.

The resulting reference leaf word is surjective, respects every unmarked
local pairing edge, and is therefore a direct input to the correct
raw-count fixed-endpoint Proposition 5.7 fibre bound.

This remains a word-sum theorem.  It does not assert a cell-integral
majorant or discharge the cell-volume and automorphism ledgers.
-/

set_option warningAsError true
set_option autoImplicit false

namespace Anderson4D

noncomputable section

open PlaneTree
open scoped BigOperators

/-- Reindex the marked-block restriction of an ambient selected cell word
by a Hepp-leaf/occupied-support equivalence. -/
def r324MarkedResidualOccupiedLeafWord
    {t : PlaneTree} {m : ℕ}
    (κp κm : PartialPairing (Fin m))
    (π : κp.singles ≃ κm.singles)
    (selected : R324ResidualCovarianceSlot κp)
    (y : Fin (2 * m) → Z4)
    (e :
      HeppLeaf t ≃
        {x // x ∈
          tupleSupport
            (r324MarkedResidualBlockWord
              κp κm π selected y)}) :
    Fin
      (2 * residualBlockOrder
        (r324MarkedResidualBlock κp κm π selected)) →
      HeppLeaf t :=
  reindexSupportWord e
    (tupleWord
      (r324MarkedResidualBlockWord
        κp κm π selected y))

/-- The marked-block leaf word is surjective onto the leaves of its
occupied-support Hepp realization. -/
theorem r324MarkedResidualOccupiedLeafWord_surjective
    {t : PlaneTree} {m : ℕ}
    (κp κm : PartialPairing (Fin m))
    (π : κp.singles ≃ κm.singles)
    (selected : R324ResidualCovarianceSlot κp)
    (y : Fin (2 * m) → Z4)
    (e :
      HeppLeaf t ≃
        {x // x ∈
          tupleSupport
            (r324MarkedResidualBlockWord
              κp κm π selected y)}) :
    Function.Surjective
      (r324MarkedResidualOccupiedLeafWord
        κp κm π selected y e) := by
  exact
    reindex_tupleWord_surjective
      (r324MarkedResidualBlockWord
        κp κm π selected y) e

/-- The occupied-label leaf word retains equality on every unmarked edge
of the canonical marked primitive pairing. -/
theorem r324MarkedResidualOccupiedLeafWord_respectsExcept
    {t : PlaneTree} {m : ℕ}
    (κp κm : PartialPairing (Fin m))
    (π : κp.singles ≃ κm.singles)
    (selected : R324ResidualCovarianceSlot κp)
    (y : Fin (2 * m) → Z4)
    (hy :
      RespectsPairingExcept
        (momentCombinedPairing κp κm π)
        (r324ResidualMarkedLowerEndpoint selected)
        (r324ResidualMarkedUpperEndpoint π selected)
        y)
    (e :
      HeppLeaf t ≃
        {x // x ∈
          tupleSupport
            (r324MarkedResidualBlockWord
              κp κm π selected y)}) :
    ∀ i :
        Fin
          (2 * residualBlockOrder
            (r324MarkedResidualBlock
              κp κm π selected)),
      i ≠ r324MarkedResidualLowerPosition
          κp κm π selected →
      i ≠ r324MarkedResidualUpperPosition
          κp κm π selected →
      r324MarkedResidualOccupiedLeafWord
          κp κm π selected y e i =
        r324MarkedResidualOccupiedLeafWord
          κp κm π selected y e
          (residualPrimitiveBlockPairing
            (momentCombinedPairing κp κm π)
            (r324MarkedResidualBlock
              κp κm π selected)
            (r324MarkedResidualBlock_isFullyPairedOn
              κp κm π selected) i) := by
  intro i hia hib
  let localWord :=
    r324MarkedResidualBlockWord
      κp κm π selected y
  have hlocal :
      RespectsPairingExcept
        (residualPrimitiveBlockPairing
          (momentCombinedPairing κp κm π)
          (r324MarkedResidualBlock κp κm π selected)
          (r324MarkedResidualBlock_isFullyPairedOn
            κp κm π selected))
        (r324MarkedResidualLowerPosition
          κp κm π selected)
        (r324MarkedResidualUpperPosition
          κp κm π selected)
        localWord :=
    r324MarkedResidualBlockWord_respectsExcept
      κp κm π selected y hy
  change
    reindexSupportWord e (tupleWord localWord) i =
      reindexSupportWord e (tupleWord localWord)
        (residualPrimitiveBlockPairing
          (momentCombinedPairing κp κm π)
          (r324MarkedResidualBlock κp κm π selected)
          (r324MarkedResidualBlock_isFullyPairedOn
            κp κm π selected) i)
  unfold reindexSupportWord
  apply e.injective
  rw [e.apply_symm_apply, e.apply_symm_apply]
  apply Subtype.ext
  exact (hlocal i hia hib).symm

/-- Direct Proposition 5.7 bound for the raw-count fibre generated by an
actual marked-block selected cell word.  Surjectivity is obtained from
the occupied finite support, never from `Z4`. -/
theorem r324MarkedResidualRawCountFiber_le_permSumRHS
    {C : ℝ} (hperm : PermSumEstimate C)
    {t : PlaneTree} {m M : ℕ}
    (κp κm : PartialPairing (Fin m))
    (π : κp.singles ≃ κm.singles)
    (selected : R324ResidualCovarianceSlot κp)
    (y : Fin (2 * m) → Z4)
    (hy :
      RespectsPairingExcept
        (momentCombinedPairing κp κm π)
        (r324ResidualMarkedLowerEndpoint selected)
        (r324ResidualMarkedUpperEndpoint π selected)
        y)
    (e :
      HeppLeaf t ≃
        {x // x ∈
          tupleSupport
            (r324MarkedResidualBlockWord
              κp κm π selected y)})
    (Nm : HeppMarking t)
    (ht : t.isValid = true)
    (hroot : rootV t ∈ BranchNodes t)
    (hadm :
      IsAdmissible Nm M
        (fun l : HeppLeaf t => (e l).1)) :
    let κB :=
      residualPrimitiveBlockPairing
        (momentCombinedPairing κp κm π)
        (r324MarkedResidualBlock κp κm π selected)
        (r324MarkedResidualBlock_isFullyPairedOn
          κp κm π selected)
    let a :=
      r324MarkedResidualLowerPosition
        κp κm π selected
    let b :=
      r324MarkedResidualUpperPosition
        κp κm π selected
    let reference :=
      r324MarkedResidualOccupiedLeafWord
        κp κm π selected y e
    ∃ n : ℕ, 2 ≤ n ∧
      (∑ w ∈
          openEdgeRawCountFixedEndpointFiber
            κB a b reference,
        heppChainWeight
          (fun l : HeppLeaf t => (e l).1) w) ≤
        (1 + (2 * (M : ℝ)) ^ 2) ^ 2 *
          permSumRHS C n t Nm
            (openEdgeArbitraryMultiplicities
              κB a b
              (r324MarkedResidualBlockPairing_lower
                κp κm π selected)
              (ne_of_lt
                (r324MarkedResidualLowerPosition_lt_upper
                  κp κm π selected))
              ((mem_primitiveFullPairings.mp
                (r324MarkedResidualBlockPairing_mem_primitiveFullPairings
                  κp κm π selected)).1)
              reference
              (r324MarkedResidualOccupiedLeafWord_surjective
                κp κm π selected y e)
              (r324MarkedResidualOccupiedLeafWord_respectsExcept
                κp κm π selected y hy e)) := by
  dsimp only
  let κB :=
    residualPrimitiveBlockPairing
      (momentCombinedPairing κp κm π)
      (r324MarkedResidualBlock κp κm π selected)
      (r324MarkedResidualBlock_isFullyPairedOn
        κp κm π selected)
  let a :=
    r324MarkedResidualLowerPosition
      κp κm π selected
  let b :=
    r324MarkedResidualUpperPosition
      κp κm π selected
  let reference :=
    r324MarkedResidualOccupiedLeafWord
      κp κm π selected y e
  have hmem :=
    r324MarkedResidualBlockPairing_mem_primitiveFullPairings
      κp κm π selected
  have hfull : κB.IsFull :=
    (mem_primitiveFullPairings.mp hmem).1
  have hprimitive : IsPrimitive κB :=
    (mem_primitiveFullPairings.mp hmem).2
  have hmLocal :
      0 <
        2 * residualBlockOrder
          (r324MarkedResidualBlock
            κp κm π selected) :=
    lt_of_le_of_lt
      (Nat.zero_le
        (r324MarkedResidualLowerPosition
          κp κm π selected).val)
      (r324MarkedResidualLowerPosition
        κp κm π selected).isLt
  exact
    rawCountFixedEndpointFiberSum_le_boxPenalty_mul_permSumRHS
      hperm reference
      (r324MarkedResidualOccupiedLeafWord_surjective
        κp κm π selected y e)
      κB a b hmLocal
      (r324MarkedResidualBlockPairing_lower
        κp κm π selected)
      (r324MarkedResidualLowerPosition_lt_upper
        κp κm π selected)
      hfull hprimitive
      (r324MarkedResidualOccupiedLeafWord_respectsExcept
        κp κm π selected y hy e)
      Nm (fun l : HeppLeaf t => (e l).1)
      ht hroot hadm

end

end Anderson4D
