#!/usr/bin/env python3
"""Generate docs/PAPER_INDEX.md: the paper <-> Lean navigation index.

The node vocabulary comes from docs/PAPER_MAP.md, whose IDs are also the
blueprint labels.  A Lean module declares which node it serves with a line
in its module docstring:

    Paper: P-5.6 -- one-line description
    Paper: infra -- one-line description        (no paper counterpart)

Modules without such a line are implementation support and are omitted from
the reader index.

Usage:
    python3 scripts/paper_index.py            regenerate the index
    python3 scripts/paper_index.py --check    exit 1 if the file is stale
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "PAPER_INDEX.md"
PAPER_MAP = ROOT / "docs" / "PAPER_MAP.md"
SRC = ROOT / "Anderson4D"

ROW = re.compile(
    r'^\|\s*(?:<a\s+id="[^"]+"></a>)?\*{0,2}'
    r"([A-Za-z]+-[A-Za-z0-9.-]+)\*{0,2}\s*\|"
)
TAG = re.compile(r"^Paper:\s*(\S+)\s*(?:[-—]+\s*)?(.*)$")

# Directory -> what part of the paper it covers, for the top of the index.
AREAS = [
    ("Combinatorics", "paper §2 — pairings, intervals, primitivity"),
    ("Continuum", "paper §2, §4 (4.1)–(4.4) — torus, Green's function, Prop 4.1"),
    ("DetParametrix/Core", "paper §3 — kernels, Def 3.1 extraction, renormalization"),
    ("DetParametrix/Paper41_Renorm", "paper §4.1 — the constant bound (3.22)"),
    ("DetParametrix/Paper42_Moment", "paper §4.2 — the moment bound (3.24)"),
    ("HeppTree", "paper §5.2–§5.3 — Hepp trees, Prop 5.6"),
    ("PermSum", "paper §5.4–§5.5 — permutation sums, Props 5.7/5.9/5.10"),
    ("Probability", "paper §2, §3 — white noise, Wick, chaos"),
    ("Parametrix", "paper §3 — the random parametrix"),
    ("Main", "paper §1 — the conditional Theorem 1.1"),
]


def paper_map_rows() -> tuple[list[str], dict[str, str]]:
    """Node IDs in paper order, and each node's paper reference."""
    order: list[str] = []
    ref: dict[str, str] = {}
    for line in PAPER_MAP.read_text().splitlines():
        m = ROW.match(line)
        if not m:
            continue
        node = m.group(1)
        if node in ref:
            continue
        cells = [c.strip() for c in line.split("|")]
        order.append(node)
        ref[node] = cells[2] if len(cells) > 2 else ""
    return order, ref


def collect() -> tuple[dict[str, list[tuple[str, str, int]]], list[str], int]:
    tagged: dict[str, list[tuple[str, str, int]]] = {}
    untagged: list[str] = []
    total = 0
    for path in sorted(SRC.rglob("*.lean")):
        total += 1
        rel = str(path.relative_to(ROOT))
        node = desc = None
        tag_line = 0
        for line_no, line in enumerate(path.read_text().splitlines()[:60], 1):
            m = TAG.match(line.strip())
            if m:
                node, desc = m.group(1), m.group(2).strip()
                tag_line = line_no
                break
        if node is None:
            untagged.append(rel)
        else:
            tagged.setdefault(node, []).append((rel, desc or "", tag_line))
    return tagged, untagged, total


def source_link(rel: str, line: int | None = None) -> str:
    """Markdown link from docs/PAPER_INDEX.md to a repository source path."""
    target = f"../{rel}"
    if line is not None:
        target += f"#L{line}"
    return f"[{rel}]({target})"


def render() -> str:
    order, ref = paper_map_rows()
    tagged, untagged, total = collect()
    out: list[str] = []
    w = out.append

    w("# PAPER_INDEX — which Lean file proves which part of the paper")
    w("")
    w("Generated by `scripts/paper_index.py`; do not edit by hand.")
    w("")
    w("This file is the generated, coarse `Paper:`-tag inventory. For the")
    w("exact paper-number ↔ public-declaration table, use")
    w("[PAPER_TO_LEAN.md](PAPER_TO_LEAN.md). Stable node IDs and dependencies")
    w("come from [PAPER_MAP.md](PAPER_MAP.md); mathematical statements and the")
    w("DAG live in the [blueprint source](../blueprint/src/content.tex).")
    w("")
    w(f"Public tagged modules: **{total - len(untagged)}**; total Lean modules: **{total}**.")
    w("Untagged implementation-support modules are intentionally omitted here;")
    w("use the source tree or `Anderson4D.lean` for the complete module inventory.")
    w("")
    w("## By directory")
    w("")
    w("| Directory | Paper |")
    w("|---|---|")
    for d, what in AREAS:
        n = len(list((SRC / d).rglob("*.lean"))) if (SRC / d).is_dir() else 0
        if n:
            w(f"| [Anderson4D/{d}/](../Anderson4D/{d}/) ({n}) | {what} |")
    w("")
    w("File-name prefixes are paper node IDs: `R322…` is node **R-322** (the")
    w("paper's bound (3.22), §4.1) and `R324…` is node **R-324** (the bound")
    w("(3.24), §4.2).  So `R324PaperStep23.lean` is *paper §4.2, Steps 2–3*.")
    w("")

    known = [n for n in order if n in tagged]
    if known:
        w("## By paper node")
        w("")
        for node in known:
            r = ref.get(node, "")
            w(f"### `{node}`" + (f" — paper {r}" if r else ""))
            w("")
            for rel, desc, tag_line in tagged[node]:
                w(f"- {source_link(rel, tag_line)}" + (f" — {desc}" if desc else ""))
            w("")

    extra = sorted(k for k in tagged if k not in ref and k != "infra")
    if extra:
        w("## Tagged with a node not in PAPER_MAP")
        w("")
        for node in extra:
            w(f"### `{node}`")
            w("")
            for rel, desc, tag_line in tagged[node]:
                w(f"- {source_link(rel, tag_line)}" + (f" — {desc}" if desc else ""))
            w("")

    if "infra" in tagged:
        w("## `infra` — no paper counterpart")
        w("")
        for rel, desc, tag_line in tagged["infra"]:
            w(f"- {source_link(rel, tag_line)}" + (f" — {desc}" if desc else ""))
        w("")

    return "\n".join(out) + "\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current == text:
            print("paper index: up to date")
            return 0
        print("paper index: STALE — run 'python3 scripts/paper_index.py'")
        return 1
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
